Update requirements.txt
The current branch gives an error of 
```
Collecting cassio (from -r requirements.txt (line 2))
  Cloning https://github.com/cassioml/cassio (to revision SL-delete-on-md-search) to /tmp/pip-install-z1r3cxp6/cassio_405815a2631f441fb78988403c0076ae
  Running command git clone --filter=blob:none --quiet https://github.com/cassioml/cassio /tmp/pip-install-z1r3cxp6/cassio_405815a2631f441fb78988403c0076ae
  WARNING: Did not find branch or tag 'SL-delete-on-md-search', assuming revision or ref.
  Running command git checkout -q SL-delete-on-md-search
  error: pathspec 'SL-delete-on-md-search' did not match any file(s) known to git
  error: subprocess-exited-with-error
  
  × git checkout -q SL-delete-on-md-search did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
```
and also both `cassio` and `langchain` have gone past the required versions so it is safer to upgrade.